name = "web-on-luyen-hai-quan"
compatibility_date = "2026-07-22"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
# Add environment variables here if needed
[env.production.vars]
R2_ACCOUNT_ID = "f0a212af83e59da75bb0e5a2f0ac029d"
R2_ACCESS_KEY_ID = "fa08b1c595678f1c352b65ed82c37ff4"
R2_BUCKET_NAME = "tai-lieu-hoc-tap"
